# https://github.com/hashicorp/vagrant/issues/8878
class VagrantPlugins::ProviderVirtualBox::Action::Network
  def dhcp_server_matches_config?(dhcp_server, config)
    true
  end
end


Vagrant.configure("2") do |config|

  # `ubuntu/cosmic64` box dowload link is dead
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"

  # Network
    # 1st adapter is default NAT used by vagrant for ssh
    config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2 # this is for host only adapter
  end

  # View the documentation for the provider you are using for more
  # information on available options.

  # below needs: `vagrant reload --provision`
  config.vm.provision "shell", inline: <<-SHELL
    # apt install -y zsh
    # apt install -y xonsh

    # sh /vagrant_data/shell/installs.sh

    
  SHELL
end
