Vagrant.configure("2") do |config|

  # `ubuntu/cosmic64` box dowload link is dead
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  end

  # View the documentation for the provider you are using for more
  # information on available options.

  # below needs: `vagrant reload --provision`
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    # docker 
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    rm -f get-docker.sh
    usermod -aG docker vagrant # needs re-login
    echo 're-login for `docker ps' & etc to work
  SHELL
end
